# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f9a4fbd0d07fd12cd61f80c9ec69520a9dad0bcd75bc8db2ce834163dbb72d34e85a61369e6eeb9fd2dec4dde379622556441a44c0ff816a99da76a24b72e11

test:
  secret_key_base: 97926fc109b1af8c3f463ca7826881cab14e5fcc46658469133ac11853cbdfce0f4ae4d817517f9a6f29c2f3456bc5891b9fcfd4bf4b61cc4e6e1e48b14a9dd8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
